# The whole toolchain is the Go toolchain, Node with pnpm, and make — nothing else to install
# (ADR-0001 §1.6). staticcheck is pinned as a tool dependency in backend/go.mod, and Biome as a
# dev dependency in web/package.json, so neither is a global install.

GENERATED := web/src/contract.generated.ts

# Where roadgen keeps the raw Overpass response, so that re-running the extraction does not re-query a
# free public service for 20 MB each time.
OVERPASS_CACHE ?= /tmp/fleetradar-overpass.json

.PHONY: dev test check generate roads

# One command from a fresh clone to a running system. The web client proxies /api to the backend, so
# the browser talks to one origin and the backend serves only the stream.
dev: web/node_modules
	@trap 'kill 0' EXIT INT TERM; \
	(cd backend && go run ./cmd/fleetradar) & \
	(cd web && pnpm dev) & \
	wait

# Go types are the single source of truth for the contract; the TypeScript is generated from them and
# the output is committed (ADR-0001 §1.4).
generate:
	cd backend && go run ./cmd/tsgen > ../$(GENERATED)

# The simulator's road network is real OpenStreetMap geometry. It is regenerated by hand and committed,
# not fetched by the build: OpenStreetMap changes daily, so a build-time fetch would make two clones of
# the same commit disagree about the world, and a clone would need the network to run at all. Needs
# internet; everything else here does not (ADR-0007 §7.3).
#
# Written aside and moved into place rather than redirected over the artefact: the shell truncates the
# target before the generator runs, so a busy Overpass — which answers 504 often enough to matter —
# would leave the committed network empty and the app unable to start.
roads:
	cd backend && go run ./cmd/roadgen -cache $(OVERPASS_CACHE) > sim/network.json.new \
		&& mv sim/network.json.new sim/network.json

test: web/node_modules
	cd backend && go test ./...
	cd web && pnpm test

# The gate, run locally and by CI from the same target. It fails if the generated TypeScript is out of date,
# because Go being the source of truth holds only while drift is visible (ADR-0009 §9.7).
check: web/node_modules
	test -z "$$(cd backend && gofmt -l .)" || { cd backend && gofmt -l . && exit 1; }
	cd backend && go vet ./...
	cd backend && go tool staticcheck ./...
	cd backend && go run ./cmd/tsgen | diff -u ../$(GENERATED) -
	cd web && pnpm check
	cd web && pnpm typecheck

web/node_modules: web/package.json web/pnpm-lock.yaml
	cd web && pnpm install
	@touch web/node_modules
